---
language: nix
nix: 2.3.1


# Use the new container infrastructure
sudo: false

install:
  # Update nix channels
  - nix-channel --add https://nixos.org/channels/nixpkgs-19.09-darwin nixpkgs
  - nix-channel --remove nixpkgs-unstable
  - nix-channel --update

  # Install ansible
  - nix-env -i ansible ansible-lint
  - nix-env -if ./dhall-1.26.1.nix

  # Check ansible version
  - ansible --version
  - ansible-lint --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-lint .
  - ansible-playbook tests/test.yml -i tests/inventory -C -D
  - scripts/dhall_check.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
